// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0fIgfFFrip-3LXqagLZKo7lsarPYVxg',
    appId: '1:207079036363:web:f838e885c2b037c89cd24e',
    messagingSenderId: '207079036363',
    projectId: 'dolbo-production',
    authDomain: 'dolbo-production.firebaseapp.com',
    storageBucket: 'dolbo-production.appspot.com',
    measurementId: 'G-9QTTVMX48F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsW1-IaPr0cyQUW6wVEAsjxbG9IAFdFRM',
    appId: '1:207079036363:android:d3c19e17403916dc9cd24e',
    messagingSenderId: '207079036363',
    projectId: 'dolbo-production',
    storageBucket: 'dolbo-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ztztdETn3ALTQaSV9yFSZahU-V-cwWs',
    appId: '1:207079036363:ios:994e8e6862c39db89cd24e',
    messagingSenderId: '207079036363',
    projectId: 'dolbo-production',
    storageBucket: 'dolbo-production.appspot.com',
    iosClientId: '207079036363-b5ag3mkridtv346njuioi023746ka8sv.apps.googleusercontent.com',
    iosBundleId: 'com.acts1soft.dolboApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ztztdETn3ALTQaSV9yFSZahU-V-cwWs',
    appId: '1:207079036363:ios:994e8e6862c39db89cd24e',
    messagingSenderId: '207079036363',
    projectId: 'dolbo-production',
    storageBucket: 'dolbo-production.appspot.com',
    iosClientId: '207079036363-b5ag3mkridtv346njuioi023746ka8sv.apps.googleusercontent.com',
    iosBundleId: 'com.acts1soft.dolboApp',
  );
}
